# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron:  '5 16 * * *'
    - cron:  '5 4 * * *'
  workflow_dispatch: {}



permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Cache pip lib 
      id: cache-pip
      uses: actions/cache@v3
      with:
        path: /usr/local/lib/python3.10/site-packages/ 
        key: cache-pip
      continue-on-error: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests bs4
    - uses: actions/checkout@v3
    - name: Cache Login Session
      id: cache-session
      uses: actions/cache@v3
      with:
        path: '${{ secrets.ACCOUNT }}.pkl'
        key: '${{ secrets.ACCOUNT }}.pkl'
      continue-on-error: true
    - name: run baha login by cli
      run: |
        python3 main.py ${{ secrets.ACCOUNT }}  ${{ secrets.PASSWORD }}
